//
//  RegisterModels.swift
//  BeCareful
//
//  Created by Carlos David Barròn Villegas on 20/08/20.
//  Copyright (c) 2020 Jose Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Register {
  // MARK: Use cases
  
  enum Something {
    struct Request {
        
    }
    struct Response {
        
    }
    struct ViewModel {
        
    }
  }
}
